config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"
  post "/", to: "home#createTransaction"
  get "/transactions", to: "transaction#index"
  delete "/transactions", to: "transaction#destroy"
  patch "/transactions", to: "transaction#update"
  get "/reports", to: "reports#index"
  get "/accounts", to: "account#index"
  post "/accounts", to: "account#create"
  delete "/accounts", to: "account#destroy"
  patch "/accounts", to: "account#update"
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
    end

    def update
        @transaction = Transaction.find(params[:transaction_id]);
        
        @account = Account.where(name: params[:account_type])[0]
        puts params
        
        @transaction[:amount] = params[:amount];
        @transaction[:classification] = params[:category];
        @transaction[:date] = params[:date];
        @transaction[:account_id] = @account[:id];

        respond_to do |format|
            if @transaction.save
                format.html { redirect_to transactions_url, notice: "Transaction was successfully updated." }
            else
                format.html { render :index, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @transaction = Transaction.find params[:transaction_id]
        @transaction.destroy

        @account = Account.find(@transaction[:account_id])
        account[:balance] -= transaction[:amount]

        respond_to do |format|
            if(accound.save)
                # TODO: subtract balance from account
                format.html { redirect_to transactions_url, notice: "Transaction was successfully deleted." }
                # redirect_back(fallback_location: root_path)
            end
        end
    end

    before_action :run_query
    def run_query
        @transactions = Transaction.all
        @accounts = Account.all
        
        account_id = nil
        
        if(params[:account_name] != "" && params[:account_name] != nil)
            account_id = Account.where(name: params[:account_name])[0][:id]
        end

        @queried_transactions = Transaction.where.not(amount: nil)

        if(account_id)
            @queried_transactions = @queried_transactions.where(account_id: account_id)
        end

        if(params[:category] != "" && params[:category] != nil)
            @queried_transactions = @queried_transactions.where(classification: params[:category])
        end

        if(params[:minAmount] != "" && params[:minAmount] != nil)
            @queried_transactions = @queried_transactions.where("amount >= ?", params[:minAmount])
        end

        if(params[:maxAmount] != "" && params[:maxAmount] != nil)
            @queried_transactions = @queried_transactions.where("amount <= ?", params[:maxAmount])
        end

        if(params[:minDate] != "" && params[:minDate] != nil)
            @queried_transactions = @queried_transactions.where("date >= ?", params[:minDate])
        end

        if(params[:maxDate] != "" && params[:maxDate] != nil)
            @queried_transactions = @queried_transactions.where("date <= ?", params[:maxDate])
        end

        limit = 20
        
        if(params[:count] != "" && params[:count] != nil)
            limit = params[:count]
        end

        @queried_transactions = @queried_transactions.take(limit)
    end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transaction/index.html.erb
<div class="header-container">
    <h1 class="title header-font">Finance App</h1>
    <ul class="nav body-font">
        <li><a href="/">Home</a></li>
        <li class="focus"><a href="/transactions">Transactions</a></li>
        <li><a href="/reports">Reports</a></li>
        <li><a href="/accounts">Accounts</a></li>
    </ul>
</div>

<div class="wide-widget-container">
    <div class="query-options">
        <h2 class="section-header">Transaction List</h2>
        <%= form_with(model: @q_transaction, url: transactions_path, method: "get") do |form| %>
            <div class="body-font"> 
                <div class="row">
                    <div class="left">
                        <%= form.label :account_name, "Account:" %>
                    </div>

                    <div class="right">
                        <%= form.text_field :account_name, list: "accounts" %>
                        <datalist id="accounts">
                            <% @accounts.each do |account| %>
                                <option value=<%=account[:name]%>>
                            <% end %>
                        </datalist>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <label for="category">Category:</label>
                    </div>

                    <div class="right">
                        <%= form.text_field :category, list: "categories" %>
                        <datalist id="categories">
                            <% @transactions.each do |transaction| %>
                                <option value=<%=transaction[:classification]%>>
                            <% end %>
                        </datalist>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <%= form.label :minAmount, "Min Amount:" %>
                    </div>

                    <div class="right">
                        <%= form.number_field :minAmount, step: ".01" %>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <%= form.label :minAmount, "Max Amount:" %>
                    </div>

                    <div class="right">
                        <%= form.number_field :maxAmount, step: ".01" %>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <%= form.label :minDate, "Start Date:" %>
                    </div>

                    <div class="right">
                        <%= form.date_field :minDate %>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <%= form.label :maxDate, "End Date:" %>
                    </div>

                    <div class="right">
                        <%= form.date_field :maxDate %>
                    </div>
                </div>

                <div class="row">
                    <div class="left">
                        <%= form.label :count, "View Limit:" %>
                    </div>

                    <div class="right">
                        <%= form.number_field :count, step: "1", value: "20" %>
                    </div>
                </div>

                <div class="row">
                    <input type="submit" value="Search">
                </div>
            </div>
        <% end %>
    </div>
    
    <div class="transaction-list body-font">
        <ul id="transactionList">
            <% @queried_transactions.each_with_index do |transaction, index| %>
                <li>
                    <span class=<%= (transaction[:amount] > 0) ? "income" : "expense" %>>$<%= "%.2f" % transaction[:amount].abs %></span>
                    <span><%= transaction[:classification] %></span>
                    <span><%= Account.find(transaction[:account_id])[:name] %></span>
                    <span><%= transaction[:date].strftime('%F') %></span>
                    <span>
                        <a onclick="editAttributes(<%=index%>, <%=transaction[:id]%>);">edit</a>
                         | 
                        <%= link_to 'delete', transactions_path(:transaction_id => transaction[:id]), method: "delete", data: { confirm: 'Are you sure?' } %>
                    </span>
                </li>
            <% end %>
        </ul>
    </div>
</div>

<%= javascript_pack_tag 'transaction' %>